"""The agents' read tools, generated by the Redis Context Retriever.

PROVIDED — not an exercise file. The exercises are the semantic model in
`src/context/models.py` and the surface in `src/context/deploy.py`; this
module is the runtime glue.

Once the model is deployed (`python -m src.context.deploy` — Section
4), the Context Retriever service exposes generated tools over MCP:
get / filter / search tools for every entity, named and described from
the model. This module asks the service for that tool list
(`list_tools`) and wraps each one as a LangChain tool that calls
`query_tool` — so whatever the service generates is exactly what the
agents can use. No tool names are hard-coded anywhere.

Until a deployment exists, the agents get a single placeholder tool that
explains what's missing, so the bot keeps working (and says why).
"""

import asyncio
import json
import logging
import re
from concurrent.futures import ThreadPoolExecutor

from langchain_core.tools import StructuredTool
from pydantic import Field, create_model

from src import config
from src.data.loader import get_redis

log = logging.getLogger("workshop")

DEPLOYMENT_KEY = config.CTX_DEPLOYMENT_KEY  # set by src.context.deploy

_JSON_TYPES = {"string": str, "integer": int, "number": float,
               "boolean": bool}


def stored_deployment() -> dict:
    """The surface id + agent key saved by the deploy endpoint."""
    try:
        return get_redis().hgetall(DEPLOYMENT_KEY) or {}
    except Exception:
        return {}


def context_read_tools() -> list[StructuredTool]:
    """The generated tool surface for the agents. Placeholder until the
    model is deployed."""
    deployment = stored_deployment()
    agent_key = deployment.get("agent_key")
    if not agent_key:
        return [_placeholder_tool()]

    try:
        listed = _run_async(_list_tools(agent_key))
    except Exception as error:
        log.warning("Context Retriever unreachable (%s) — agents get the "
                    "placeholder tool.", error)
        return [_placeholder_tool()]

    # count_* aggregates have no customer scope — a chat agent asked
    # "do I have offers?" must not answer with the bank-wide count, so
    # the agents don't get them (they stay visible via list_tools).
    tools = [_wrap_mcp_tool(agent_key, spec) for spec in listed
             if not spec["name"].startswith("count_")]
    log.info("Context Retriever: %d generated tools loaded (%s)",
             len(tools), ", ".join(t.name for t in tools))
    return tools


def _run_async(coro):
    """`asyncio.run`, but safe when a loop is already running: the api
    builds its tools during FastAPI startup — inside uvicorn's event
    loop — where `asyncio.run()` is illegal, so fall back to a worker
    thread that owns its own loop."""
    try:
        asyncio.get_running_loop()
    except RuntimeError:
        return asyncio.run(coro)
    with ThreadPoolExecutor(max_workers=1) as pool:
        return pool.submit(asyncio.run, coro).result()


# Each call gets a fresh client: these coroutines run under their own
# event loop, and the MCP connection opened on one loop cannot be
# reused on the next. `async with` opens and closes it cleanly.

async def _list_tools(agent_key: str) -> list[dict]:
    from context_surfaces import UnifiedClient

    async with UnifiedClient() as client:
        return await client.list_tools(agent_key)


async def _query_tool(agent_key: str, name: str, arguments: dict):
    from context_surfaces import UnifiedClient

    async with UnifiedClient() as client:
        return await client.query_tool(agent_key, name, arguments)


def _wrap_mcp_tool(agent_key: str, spec: dict) -> StructuredTool:
    """One generated MCP tool -> one LangChain tool. Name, description,
    and argument schema all come from the service."""
    name = spec["name"]
    schema = spec.get("inputSchema") or spec.get("input_schema") or {}
    properties = schema.get("properties", {})
    required = set(schema.get("required", []))

    # Identity injection (graph.py) keys on an argument literally named
    # customer_id — but the generated tools name theirs generically:
    # filter_*_by_customer_id takes `value`, get_customer_by_id takes
    # `id`. Alias those to customer_id so the session's verified
    # customer is enforced on generated tools too, not just hand-written
    # ones.
    customer_arg = None
    if re.fullmatch(r"filter_.+_by_customer_id", name) and \
            "value" in properties:
        customer_arg = "value"
    elif name == "get_customer_by_id" and "id" in properties:
        customer_arg = "id"

    fields = {}
    for arg, arg_schema in properties.items():
        public = "customer_id" if arg == customer_arg else arg
        arg_type = _JSON_TYPES.get(arg_schema.get("type", "string"), str)
        default = ... if arg in required else None
        fields[public] = (arg_type if arg in required else arg_type | None,
                          Field(default,
                                description=arg_schema.get("description",
                                                           "")))
    args_model = create_model(f"{name}_args", **fields)

    def run(**kwargs) -> str:
        if customer_arg and "customer_id" in kwargs:
            kwargs[customer_arg] = kwargs.pop("customer_id")
        arguments = {k: v for k, v in kwargs.items() if v is not None}
        result = _run_async(_query_tool(agent_key, name, arguments))
        return result if isinstance(result, str) else json.dumps(
            result, default=str)

    return StructuredTool(
        name=name,
        description=spec.get("description", name),
        args_schema=args_model,
        func=run,
    )


def _placeholder_tool() -> StructuredTool:
    def missing(query: str = "") -> str:
        return ("The Context Retriever is not deployed yet — the bank's "
                "data model hasn't been pushed to the service. Complete "
                "the Section 4 exercise (src/context/models.py, then run "
                "python -m src.context.deploy from the Terminal).")
    return StructuredTool.from_function(
        func=missing,
        name="bank_data_lookup",
        description="[not available yet] Bank data access — the Context "
                    "Retriever's semantic model is not deployed "
                    "(Section 4 exercise).")
