"""The agents' read tools, generated by the Redis Context Retriever.

PROVIDED — not an exercise file. The exercise is the semantic model in
`src/context/models.py`; this module is the runtime glue.

Once the model is deployed (POST /api/context/deploy — Section 4), the
Context Retriever service exposes generated retrieval tools over MCP:
get / filter / search tools for every entity, named and described from
the model. This module asks the service for that tool list
(`list_tools`) and wraps each one as a LangChain tool that calls
`query_tool` — so whatever the service generates is exactly what the
agents can use. No tool names are hard-coded anywhere.

Until a deployment exists, the agents get a single placeholder tool that
explains what's missing, so the bot keeps working (and says why).
"""

import asyncio
import json
import logging

from langchain_core.tools import StructuredTool
from pydantic import Field, create_model

from src import config
from src.data.loader import get_redis

log = logging.getLogger("workshop")

DEPLOYMENT_KEY = "ctx:deployment"  # local Redis hash set by /api/context/deploy

_JSON_TYPES = {"string": str, "integer": int, "number": float,
               "boolean": bool}


def stored_deployment() -> dict:
    """The surface id + agent key saved by the deploy endpoint."""
    try:
        return get_redis().hgetall(DEPLOYMENT_KEY) or {}
    except Exception:
        return {}


def context_read_tools() -> list[StructuredTool]:
    """The generated tool surface for the agents. Placeholder until the
    model is deployed."""
    deployment = stored_deployment()
    agent_key = deployment.get("agent_key")
    if not agent_key:
        return [_placeholder_tool()]

    from context_surfaces import UnifiedClient

    client = UnifiedClient()
    try:
        listed = asyncio.run(client.list_tools(agent_key))
    except Exception as error:
        log.warning("Context Retriever unreachable (%s) — agents get the "
                    "placeholder tool.", error)
        return [_placeholder_tool()]

    tools = [_wrap_mcp_tool(client, agent_key, spec) for spec in listed]
    log.info("Context Retriever: %d generated tools loaded (%s)",
             len(tools), ", ".join(t.name for t in tools))
    return tools


def _wrap_mcp_tool(client, agent_key: str, spec: dict) -> StructuredTool:
    """One generated MCP tool -> one LangChain tool. Name, description,
    and argument schema all come from the service."""
    name = spec["name"]
    schema = spec.get("inputSchema") or spec.get("input_schema") or {}
    properties = schema.get("properties", {})
    required = set(schema.get("required", []))

    fields = {}
    for arg, arg_schema in properties.items():
        arg_type = _JSON_TYPES.get(arg_schema.get("type", "string"), str)
        default = ... if arg in required else None
        fields[arg] = (arg_type if arg in required else arg_type | None,
                       Field(default,
                             description=arg_schema.get("description", "")))
    args_model = create_model(f"{name}_args", **fields)

    def run(**kwargs) -> str:
        arguments = {k: v for k, v in kwargs.items() if v is not None}
        result = asyncio.run(client.query_tool(agent_key, name, arguments))
        return result if isinstance(result, str) else json.dumps(
            result, default=str)

    return StructuredTool(
        name=name,
        description=spec.get("description", name),
        args_schema=args_model,
        func=run,
    )


def _placeholder_tool() -> StructuredTool:
    def missing(query: str = "") -> str:
        return ("The Context Retriever is not deployed yet — the bank's "
                "data model hasn't been pushed to the service. Complete "
                "the Section 4 exercise (src/context/models.py, then "
                "POST /api/context/deploy).")
    return StructuredTool.from_function(
        func=missing,
        name="bank_data_lookup",
        description="[not available yet] Bank data access — the Context "
                    "Retriever's semantic model is not deployed "
                    "(Section 4 exercise).")
